### get all
GET http://localhost:3000/api/users

### get one
GET http://localhost:3000/api/users/1

### create
POST http://localhost:3000/api/users 
Content-Type: application/json

{
    "nombre":  "Mateo", 
    "apellido": "Medon", 
    "email": "mateemedon@gmail.com", 
    "contraseña": "mm02022002",
    "telefono": "2473464989"
}


### modificar recurso completo e idempotente
PUT http://localhost:3000/api/users/1 
Content-Type: application/json

{
    "nombre":  "Juampi", 
    "apellido": "Binomio", 
    "email": "jb999@gmail.com", 
    "contraseña": "jb02022002",
    "telefono": "5434150654"
}

### modificar recurso parcial
PATCH http://localhost:3000/api/users/1
Content-Type: application/json

{
    "email":  "juanbinomio@gmail.com", 
    "contraseña": "jb01011001"
}

###borrar recurso
DELETE http://localhost:3000/api/users/3